# Generated by Django 4.2.3 on 2023-07-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mene',
            new_name='Menu',
        ),
    ]
